# Generated by Django 4.2.7 on 2024-04-07 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_service_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='housing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='married',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mother_firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mother_lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='working',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
